# Generated by Django 4.2.5 on 2023-09-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippinfAddress',
            new_name='ShippingAddress',
        ),
    ]
